<?php
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\Html;
use Stephane888\Debug\Repositories\ConfigDrupal;

/**
 *
 * @file
 * Primary module hooks for Login rx vuejs module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
function login_rx_vuejs_form_user_login_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //
}

/**
 *
 * @param string $key
 * @param string $message
 * @param array $params
 */
function login_rx_vuejs_mail($key, &$message, $params) {
  switch ($key) {
    case 'login_rx_vuejs_send_mail':
      $conf = ConfigDrupal::config('system.site');
      $message['from'] = $conf['mail'];
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      // Send html
      if (!empty($message['headers']['Content-Type'])) {
        $contentType = explode(";", $message['headers']['Content-Type']);
        $contentType[0] = "text/html";
        $message['headers']['Content-Type'] = implode(';', $contentType);
      }
      break;
  }
}

/**
 *
 * @param
 *        $variables
 */
function login_rx_vuejs_preprocess_page(&$variables) {
  $keys = [
    '#sorted',
    '#theme_wrappers',
    '#region',
    'attributes'
  ];
  $route_name = \Drupal::routeMatch()->getRouteName();
  //
  if ($route_name == "user.login" || $route_name == "user.register") {
    if (isset($variables['page']['content'])) {
      $blocks = $variables['page']['content'];
      foreach ($blocks as $i => $value) {
        if (!in_array($i, $keys)) {
          unset($variables['page']['content'][$i]);
        }
      }
      $variables['page']['content']['login_rx_vuejs'] = [
        '#theme' => "login_rx_vuejs"
      ];
      // get config.
      $config = \Drupal::config('login_rx_vuejs.settings')->getRawData();
      if (isset($config['environ_run']) && $config['environ_run']) {
        $variables['page']['content']['login_rx_vuejs']['#attached']['library'][] = 'login_rx_vuejs/login_register';
      }
      else {
        $variables['page']['content']['login_rx_vuejs']['#attached']['library'][] = 'login_rx_vuejs/login_register_dev';
      }
    }
  }
}

/**
 * Pour une raison inconnu, ilne fonctionne pas en ligne.
 *
 * @param
 *        $variables
 */
/*
 * function login_rx_vuejs_preprocess_page__user(&$variables){
 * $keys = [
 * '#sorted',
 * '#theme_wrappers',
 * '#region',
 * 'attributes'
 * ];
 * $route_name = \Drupal::routeMatch()->getRouteName();
 * if($route_name == "user.login" || $route_name == "user.register"){
 * if(isset( $variables['page']['content'] )){
 * $blocks = $variables['page']['content'];
 * foreach( $blocks as $i => $value ){
 * if(! in_array( $i, $keys )){
 * unset( $variables['page']['content'][$i] );
 * }
 * }
 * $variables['page']['content']['login_rx_vuejs'] = [
 * '#theme'=> "login_rx_vuejs"
 * ];
 * $variables['page']['content']['login_rx_vuejs']['#attached']['library'][] =
 * 'login_rx_vuejs/login_register';
 * }
 * }
 * }
 * /*
 */
/**
 * -
 */
function login_rx_vuejs_theme($existing, $type, $theme, $path) {
  return [
    'login_rx_vuejs' => [
      'render element' => 'element',
      'preprocess functions' => [
        'template_preprocess_ogin_rx_vuejs'
      ],
      'file' => 'login_rx_vuejs.theme.inc'
    ]
  ];
}

